# Learning Python3 the Hard Way. Excercise 34. Accessing Elements of Lists.

animals = ['bear', 'python3.6', 'peacock', 'kangaroo', 'whale', 'platypus']

print("The animal at 1.")
print("The animal at 1 is the second animal and is a python.")
print("The second animal is at 1 and is a python.")
print(animals[1])
print("The third animal.")
print("The third animal is at 2 and is a peacock.")
print("The animal at 2 is the third animal and is a peacock.")
print(animals[2])
print("The first animal.")
print("The first animal is at 0 and is a bear.")
print("The animal at 0 is the first animal and is a bear.")
print(animals[0])
print("The animal at 3.")
print("The animal at 3 is the fourth animal and is a kangaroo.")
print("The fourth animal is at 3 and is a kangaroo.")
print(animals[3])
print("The fifth animal.")
print("The fifth animal is at 4 and is a whale.")
print("The animal at 4 is the fifth animal and is a whale.")
print(animals[4])
print("The animal at 2.")
print("The animal at 2 is the third animal and is a peacock.")
print("The third animal is at 2 and is a peacock.")
print(animals[2])
print("The sixth animal.")
print("The sixth animal is at 5 and is a platypus.")
print("The animal at 5 is the sixth animal and is a platypus.")
print(animals[5])
print("The animal at 4.")
print("The animal at 4 is the fifth animal and is a whale.")
print("The fifth animal is at 4 and is a whale.")
print(animals[4])
